Avoid tokenizer exceptions for qualified expressions
Paebbels/pyVHDLParser pull request #56
Opened 2023-06-27 11:49 UTC by skaupper

Currently qualified expressions trigger a tokenizer exception.

This PR should take care of these, by recognizing that the character pattern `'(` may not be followed by another single quote (which would produce the character literal `'('`). In those cases both characters are output as instances of `CharacterToken`.

An additional test case ensure a correct parsing of qualified expressions (e.g. `UNSIGNED'(x"0")`) and the relevant character literal `(`.

2023-06-27 17:34 UTC, Paebbels requested changes
Should we have a test for these sequences:
```
foo'('0')
foo'('(')
```

2023-06-27 17:34 UTC, Paebbels commented on pyVHDLParser/Token/Parser.py
> +					if all(c in __ALPHA_CHARACTERS__ for c in buffer):
Is `all` really faster then two single lookups?

2023-06-27 17:34 UTC, Paebbels commented on pyVHDLParser/Token/Parser.py
> +					if buffer[0] == "(": # Relevant for qualified expressions
```suggestion
					if buffer[0] == "(":  # Relevant for qualified expressions
```
Python (styling) requires at least 2 spaces before `#`. I'm following Python coding styles loosely, but this is a good rule :).

2023-06-27 17:35 UTC, Paebbels commented
@skaupper are you planning more fixes like this or should I prepare for a release of that code to `main`?

2023-06-28 08:37 UTC, skaupper commented on pyVHDLParser/Token/Parser.py
> +					if all(c in __ALPHA_CHARACTERS__ for c in buffer):
The reason I changed the checks to a `for` loop and the call to `all` is, because the `buffer` may contain 1 or 2 items by now (the branch above strips the `'('` character from the buffer).

If that will still be needed after fixing the test cases you mentioned, I will make some performance comparisions as well.

2023-06-28 08:46 UTC, skaupper commented
> Should we have a test for these sequences:
> 
> ```
> foo'('0')
> foo'('(')
> ```

Well, without trying it I am pretty sure these cases will fail with the current solution. 
It will probably be tricky to unambiguously support all variations of character literals, qualified expressions and attributes. Maybe with a deeper lookahead?

Can you think of an example of the form `foo'(',')'` being valid VHDL?

I will have another look at it!

2023-06-28 08:53 UTC, skaupper commented
> @skaupper are you planning more fixes like this or should I prepare for a release of that code to `main`?

Currently I focus on fixing things which occur while parsing some generated VHDL sources. As of now it seems qualified expressions are the last issue with the tokenizer for my use cases.

I may have a look into some issues with the block parser afterwards (e.g. #9 and #16). Personally, I do not need a release though.

2023-06-29 20:26 UTC, Paebbels commented
> Can you think of an example of the form foo'(',')' being valid VHDL?

I don't think so.

2023-06-30 13:26 UTC, skaupper commented
> Type, qualified expression on character `,` followed by an attribute ...
> 
> `character'(',')'length`

After digging through the LRM and using ModelSim to confirm some ideas, it seems like `character'(',')'length` is not valid VHDL, since a qualified expression is neither a _name_ nor a _function_call_ according to the syntax. 

On the other hand these snippets ARE valid VHDL: `character'(''')` and `'''`, both representing a value of `'`.

A similiar issue arises with the string literal `"a""b"` representing the string `a"b` (both `a` and `b` can be omitted for a string literal of `""""`) but that should be part of another issue/PR, i guess.

2023-06-30 13:29 UTC, skaupper commented
For this PR, I will focus on solving the `foo'('(')` problem. Using a look-behind tokens seems promising, since `'(` may only be a qualified expression if a `WordToken` preceeds it (any counter examples are welcome).

Any shenanigans involving `'''` and `""""` should probably be handled in a separate PR.

2023-06-30 18:49 UTC, Paebbels commented
Please remove the draft state when ready for review / merge.

2023-07-08 21:15 UTC, merged